# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccsync" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "5845a414644a36b00286d6c7a9d751822b80a4331ff462efffb37f223132ec5a"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "178b93289d469c317ffdb150f9a349be3354b5cbfb39e71439983e21d965e9c5"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05fdb2185047a6af478489a4a3686811d203b96d0367928449db2cd908f2816b"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e36791da9e4e1a91f0f1df80776fa074342f27e0e0c4380a4a82a0711f6ed24"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_linux_arm64.tar.gz"
    end
  end

  name "ccsync"
  desc "Selective, encrypted, multi-device sync for Claude Code session history"
  homepage "https://github.com/melihemreguler/claude-code-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccsync"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccsync"]
  end

  # No zap stanza required

end
