# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccsync" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "8381d56a6cb17d7852a251d502410d98303be1d43f20a6629be8fb2331ced22f"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5308e068055bb6c550f07c2ad2d0597b2b935f4959fb926f5f72b4c771e1de17"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df9930a7cfb581dd4b7619bab5a5ac4dfae64d9f200fca1dbfbccf16fa898ebc"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e213e972bce82188a11d25686a5124f1b2f1f9f582a8193508030aa1fbac9427"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_linux_arm64.tar.gz"
    end
  end

  name "ccsync"
  desc "Selective, encrypted, multi-device sync for Claude Code session history"
  homepage "https://github.com/melihemreguler/claude-code-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccsync"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccsync"]
  end

  # No zap stanza required

end
