# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccsync" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "a96a9fee8b6b6bb8bcb438a7862b318610a894110258e84c1b6302a3d94862e0"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "84e647855771e169974ed57bf1d976d20e14473595cd16607f2a0eacfeccbd03"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41454c206b4120dc451d587d440daf9b0dfca83e4b64f4e7bb59b2a1c881fb7f"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b91ae84a2cbf96ce29eef812e50787719e3c50305edb9ba809bd8cc2005aa8e"
      url "https://github.com/melihemreguler/claude-code-sync/releases/download/v#{version}/ccsync_linux_arm64.tar.gz"
    end
  end

  name "ccsync"
  desc "Selective, encrypted, multi-device sync for Claude Code session history"
  homepage "https://github.com/melihemreguler/claude-code-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccsync"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccsync"]
  end

  # No zap stanza required

end
